[package]
name = "roblox_browser"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
base64 = "0.22.1"
byteorder = "1.5.0"
bytes = "1.6.0"
crossbeam = "0.8.4"
headless_chrome = "1.0.9"
image = "0.25.1"
rayon = "1.10.0"
ringbuf = "0.4.0"
tiny_http = "0.12.0"
